name: bloc_news_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # state management
  flutter_bloc: ^8.1.5

  # compares dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.7.0

  # dateFormate
  intl: ^0.19.0

  # localDatabase
  floor: ^1.5.0

  # http client
  retrofit: ^4.1.0

  # Hooks
  flutter_hooks: ^0.20.5

  # image cache
  cached_network_image: ^3.3.1

  # icons
  ionicons: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.10


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
